# Generated by Django 2.0.2 on 2020-03-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='key',
            field=models.SlugField(max_length=110, unique=True, verbose_name='Nombre Clave'),
        ),
    ]
